# Generated by Django 3.2.9 on 2021-11-25 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_no', models.CharField(blank=True, max_length=10, verbose_name='nr lokalu')),
                ('building', models.CharField(max_length=10, verbose_name='nr budynku')),
                ('street', models.CharField(max_length=40, verbose_name='ulica')),
                ('city', models.CharField(max_length=40, verbose_name='miasto')),
                ('zip_code', models.CharField(max_length=10, verbose_name='kod pocztowy')),
            ],
            options={
                'verbose_name': 'adres',
                'verbose_name_plural': 'adresy',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='numer zamówienia')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='data utworzenia')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_addresses', to='shops.address', verbose_name='adres do faktury')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_addresses', to='shops.address', verbose_name='adres do wysyłki')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='kwota wysyłki')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='nazwa')),
                ('capacity', models.IntegerField(verbose_name='ilość produktów')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.address', verbose_name='adres')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='nazwa')),
                ('in_stock', models.IntegerField(verbose_name='stan magazynowy')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cena produktu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.order', verbose_name='zamówienie')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.status', verbose_name='status'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False, verbose_name='Ukryty')),
                ('deleted', models.BooleanField(default=False, verbose_name='Usunięty')),
                ('number', models.CharField(max_length=50, verbose_name='numer')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='data utworzenia')),
                ('payment_date', models.DateField(verbose_name='termin płatności')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
